name: Python Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  linter_and_code_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: '1.8.2'

      - name: Install dependencies
        run: poetry install --only=dev

      - name: Lint and check
        run: make lint
