name: Python Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: '1.8.2'

      - name: Install dependencies
        run: poetry install --only=main,test

      - name: Run tests with coverage
        run: make test

      - name: Check directory path
        run: |
          ls -l /home/runner/work/leetcode-craft/
          ls -l /home/runner/work/leetcode-craft/leetcode-craft/leetcode_craft
          pwd

      - name: Check directory path 2
        run: |
          ls -l /home/runner/work/leetcode-craft/leetcode-craft/

      - name: Check coverage.xml contents
        run: cat /home/runner/work/leetcode-craft/leetcode-craft/coverage.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
