name: Python Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test_and_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: '1.8.2'

      - name: Install dependencies
        run: poetry install --only=main,test

      - name: Run tests with coverage
        run: make test
