name: Semantic PR
permissions:
  pull-requests: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  semantic_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        name: Semantic Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
